// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uivbxdnnlumyeuyelmjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpdmJ4ZG5ubHVteWV1eWVsbWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDc0NzAsImV4cCI6MjA3MDM4MzQ3MH0.xN3dNoZjEUd7mLk6U-joIybshqV9DveMFLEdABUqmBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});